version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust-crud-app
    ports:
      - 5432:5432

networks:
  postgres:
    driver: bridge